language: ruby
addons:
  postgresql: '9.3'
script:
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rspec
before_script:
- psql -c 'create database this_or_that_test;' -U postgres
deploy:
  provider: heroku
  app: arcane-sierra-1279
  api_key:
    secure: m77yDnEluXERDyVU73R8sjMzDRskD2C+tL54mzxWenAb02eYtfIOiuzM6hUQKjdb/OSx4VOwAdLpo4E854UrgQULMBhNw+EeKA22OGCNceexSPvLupn+XWwmkLALycAWtqUgaW1c20HrJuqFYWkR3I2Yn7lYuCuQGqnuiosYw4zZWuWy2pdpc2FoWhQo77cRM7UKOPgz8wJakBaNqPRmkbYTtcMq8NeMQWMUhzvnpaOddx37lQ7eRfGhCpHegp1155AgsRNoEwgAg7qyK78x1BC4qL6sq3PpXOZCiV3pKxosHKh8rrGVL9ohVzDIwbQpZ2jA7vnIUZYdUPg9ne4eTRnuRAwS4yBPRfhhsiGZx86WQVc5245ldBW/sn+lsGy/mPmYdyZUs/aBsobP6mu5TX0KEnFJkqiau0JqLRRngNM4McHOecZtjjFNpBqhIBe3NnoqsRbdCACZBgjB9c6FN1k/GA/NBf3uKNTtRD5jTsRfW7jimjESkSCJMsDpP9O2cOlBJVlK0T5O3zpbmoOE9+tjqvT6nMhS8E4JvaSnfv/8Mykn7HJbZWOoF/9MGOPvDjh+z4DWc6e5fgS50lp5quUIRR6xRV7peqgZaSUIqchtao5SIS1PvyTbzX2XBBzu5ncwwtTlb34t/1v1DXQBwtG9QJQo5MaYvRSKsYnvYBU=
  run:
    - 'rake db:migrate'
    - restart
    - 'rake cleanup'
